DROP TABLE IF EXISTS TB_GUITARS;
CREATE TABLE TB_GUITARS (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  BRAND TEXT NOT NULL,
  COLOR TEXT NOT NULL
)

---create
INSERT INTO TB_GUITARS (BRAND, COLOR)
VALUES 
    ('FENDER', 'BLUE'),
    ('FENDER', 'RED'),
    ('FENDER', 'WITE')

---read
SELECT * FROM TB_GUITARS;
SELECT * FROM TB_GUITARS WHERE COLOR= 'RED'
SELECT BRAND FROM TB_GUITARS WHERE COLOR= 'RED'